### ISSUE TITLE
Theme section

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/protonmail-settings#17]
![Capture d’écran 2019-04-15 à 12 08 52](https://user-images.githubusercontent.com/1345786/56124586-42ebb000-5f77-11e9-80b3-e0827d4e2236.png)
![Capture d’écran 2019-04-15 à 12 08 46](https://user-images.githubusercontent.com/1345786/56124599-4848fa80-5f77-11e9-870b-0c90c715c95e.png)
![Capture d’écran 2019-04-15 à 12 08 55](https://user-images.githubusercontent.com/1345786/56124601-48e19100-5f77-11e9-98bc-81b1daec04b3.png)

**Comment by econdepe** [comment]
I see a bit of conflict between what is probably the desired functionality and the design https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5c4eb40ebfb873bf2b204cd1 . Let me explain:

According to the design and how the `ObserverSections` and `SubSidebar` components work, for the themes we would need three components: `ThemesSection`, `ThemeEditorSection` and `CustomSection`. These would be passed to `ObserverSections`, that would map them into the sidebar. However these three components need to talk to each other as I presume we would like to, say, update the way the themes look in `ThemeSection` if the user changes it in `ThemeEditorSection`. For that we need a parent component that has all three as children. But this would ruin the `ObserverSections` and `SubSidebar` combined functionality.

One solution is to modify `ObserverSections` so that it would accept a parameter in order to do a recursive mapping for components whose parameter indicate so.

**Comment by econdepe** [comment]
New wireframes
[Web - Settings - Themes.pdf](https://github.com/ProtonMail/protonmail-settings/files/3120389/Web.-.Settings.-.Themes.pdf)
