### ISSUE TITLE
Click on text triggers the switch

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonmail-settings#42]
**Steps to reproduce**
1. Go to Appearance
2. Click on use sticky labels text.
3. Notice how the the switch changed the state.

**Screenshot**
![StickyL](https://user-images.githubusercontent.com/11393457/58568573-cfef7d80-8234-11e9-9499-3976b9767084.gif)

**Additional info**
This is happening on all switch elements.

**Comment by nico3333fr** [comment]
Yes, this is intended, the label triggers the switch. 

Basically the switch is a "fake" checkbox. For accessibility reasons, we have to link this field to its label, in order to be properly vocalized. As the label is designed to be clickable (which is also a good help for people that click not exactly on the checkbox), this gives this behaviour.

Imho, I would let it like this. 
If you really think this is an issue, we may use the helper `cursor-default` on the label to let the standard cursor.
